version: "3.9" # Use the appropriate version of Docker Compose

networks:
  darknet:

services:
  chromaDB:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    container_name: chromaDB
    networks:
      - darknet
  
  chat-server:
    build:
      context: .
      # args:
    environment:
      - NODE_CONFIG=${NODE_CONFIG}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "3000:3000"
    container_name: chat-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 50s
      timeout: 10s
      retries: 5
    networks:
      - darknet